schema: LeanDeep
version: '4.0'
id: SEM_WHATABOUTISM_DEFLECTION
name: SEM_WHATABOUTISM_DEFLECTION
family: SEM
lang: de
description: Counter-Justification
composition_rule:
  requires_prior:
  - ATO_DIRECT_ACCUSATION|SEM_CRITICISM_PERSONAL_ATTACK
  evidence_window: ≤2 turns
  compose_of_at_least_two_distinct_ATOs: true
  typical_ATOs:
  - ATO_GOTTMAN_DEFENSIVENESS
  - ATO_BLAME_SHIFT
  - ATO_PROJECTION_2P_TRAIT
  - ATO_TOPIC_SWITCH_ADVERSATIVE
  - ATO_DISMISSIVE_DOWNPLAY
  discourse_cues:
  - aber du …
  - und du …
  - was ist mit …
  - ihr/andere machen doch auch …
  exclusions:
  - On-Topic-Vergleich mit unmittelbarer Verhaltensreparatur
  - Beleggestützte Kontextpräzisierung (keine Schuldumkehr)
tags:
- semantic
- deflection
- defensiveness
- tu-quoque
triggers:
- type: regex
  value: (?i)^(aber|und) du (hast|machst|bist)
- type: regex
  value: (?i)was ist mit (dir|euch|deinem .*|[a-zäöüß]+)\?
- type: regex
  value: (?i)(andere|alle) machen das doch auch
- type: regex
  value: (?i)du hast (gar kein|kein) recht .* (zu sagen|zu behaupten)
- type: regex
  value: (?i)und (bei|als) dir war es (doch|ja) (genauso|schlimmer)
positives:
- Aber du kommst doch auch ständig zu spät.
- Und du hast mich letzte Woche auch ignoriert.
- Was ist mit deinem Versprechen vom Montag?
- Andere Teams überziehen ihre Deadlines auch dauernd.
- Du hast gar kein Recht, das zu behaupten – du hast selbst gelogen.
- Und als du dran warst, war es doch noch schlimmer.
- Was ist mit dem Chaos in deinen Tasks?
- Du bist doch auch nicht besser.
- Und du hast gestern selbst gegen die Regeln verstoßen.
- Was ist mit den Bugs, die du offen gelassen hast?
- Alle machen das so – warum stichst du mich raus?
- Und letztes Quartal hast du das Gleiche gemacht.
- Wie war das nochmal mit deinem Fehlkauf?
- 'Bevor du mich kritisierst: Was ist mit deiner Präsentation neulich?'
- Und dein Ton vorhin war auch respektlos.
- Was ist mit den Mails, die du ignoriert hast?
- Du hast selbst keine perfekte Dokumentation, also bitte.
- Und bei deinem Projekt war es genauso chaotisch.
- Was ist mit deiner Zusage vom Freitag?
- Du bist doch der Letzte, der das sagen sollte.
- Und du hast mir auch nie vorher Bescheid gegeben.
- Was ist mit deinem Anteil an dem Problem?
- Andere Abteilungen liefern auch zu spät.
- Und du warst beim Kunden auch unvorbereitet.
- Was ist mit den Kostenüberschreitungen in deinem Bereich?
- Aber du hast den Prozess doch selbst umgangen.
- Und als ich Hilfe brauchte, warst du nicht da.
- Was ist mit deinen verpassten Reviews?
negatives:
- Du hast recht; ich schaue mir das an und verbessere es.
- Dein Punkt stimmt – lass uns konkrete Beispiele sammeln.
- 'Mir fällt ein Vergleich ein, der die Anforderung klärt: [on-topic, sachlich].'
- Ich übernehme meinen Anteil; was wäre ein nächster Schritt?
constraints:
- Fire nur, wenn (a) vorher explizite Kritik/Korrektur vorliegt und (b) die Antwort
  keine eigene Verantwortung übernimmt.
- Kein Treffer, wenn der Vergleich direkt zur Reparatur führt (z. B. Entschuldigung
  + To-Do).
- Kein Treffer, wenn die Referenz klar on-topic ist (gleiche Situation, gleiche Zeit,
  gleiche Personen) und zur Klärung dient.
diagnostics:
  false_positive_risks:
  - Legitime On-Topic-Gegenbelege in sachlicher Form
  - Meta-Hinweis auf beidseitige Standards mit anschließendem Commit
  adjacent_markers:
  - SEM_DEFENSIVENESS_SHIFT
  - SEM_MINIMIZATION
  - SEM_BLAME_SHIFT
  - ATO_GOTTMAN_DEFENSIVENESS
  - ATO_TOPIC_SWITCH_ADVERSATIVE
examples_windowing:
  prior_message: Direkte Kritik/Anschuldigung an Sprecher A
  reply_message: Sprecher A antwortet mit Gegenanschuldigung/Relativierung
  max_gap: ≤1 dazwischenliegende Nachricht ohne Themenwechsel
